### ISSUE TITLE
Multi-animation dotLottie creation GUI

### ISSUE THREAD

**Issue by astridman** [dotlottie/dotlottie-js#33]
Do any of the devs have a site available to create the multi-animation dotLottie(s)? I attempted to setup the dotlottie-js package but I'm a weekend-dev and eventually hit the wall.

https://docs.lottiefiles.com/dotlottie-player/usage/multi-animation-.lotties

**Comment by theashraf** [comment]
Hi @astridman 
Currently, we don't have a site specifically designed for creating multi-animation dotLottie files. If you could share the specific challenges or errors you encountered while setting up the dotlottie-js package.I'll do my best to guide you through them

**Comment by samuelOsborne** [comment]
Hey @astridman please check out our dotLottie playground - you can drag and drop .json files to create your multi-animation dotLottie!

[https://dotlottie.github.io/player-component/](https://dotlottie.github.io/player-component/)

Cheers! 🎉

**Comment by astridman** [comment]
Hi @samuelOsborne thank so much for this, although I wasn't able to load in or drag on multiple dotLottie animations. 

And I couldn't get JSON files to load at all. 

Am I missing a step?

**Comment by samuelOsborne** [comment]
@astridman Could you email me the json files so I can see what the problem is with them ?

 sam@lottiefiles.com
 
 For the moment the playground allows you to drag multiple .json files to combine them, not merge dotLotties together however that is a function of this library
